# 공통 설정만 있는 야말파일

jwt:
  secret: "change-this-to-a-very-long-random-secret-key-for-final-project-2026"
  access-token-expiration-ms: 60000
  refresh-token-expiration-ms: 1209600000

solapi:
  enabled: true
  api-key: "NCSIFFEJP0BPVSQU"
  api-secret: "JW2CYTPS4P7NLXNA9PAUN0VCBVGJ2IK0"
  from-phone: "01020660376"
  base-url: "https://api.solapi.com"

spring:
  application:
    name: board-service

  profiles:
    active: local

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  messages:
    basename: messages.validation
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml

logging:
  level:
    '[com.spring.app]': debug

server:
  port: 8002
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-part-count: 30

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


portone:
  impCode: imp13783325
  apiKey: 6685577616083070
  apiSecret: iur2e8plZSGlGi8Tkkaak8QgJS3o8NMaYrBredEzJUtSSpRIKrXIRwbl0hiLIiyvxtQWe4G1p8GTt6v4

app:
  login-url: /user-service/member/login